ru:
  account_subscribes:
    edit:
      title: Изменить
    hint_html: "<strong>Что такое подписка на аккаунт?</strong> Заместить доступные всем посты из указанного аккаунта на главную страницу или составить список ленты. Объектами являются посты, полученные сервером (из распределенной ленты)."
    new:
      title: Добавить новый подписанный аккаунт
  domain_subscribes:
    edit:
      title: Изменить
    hint_html: "<strong>Что такое подписка на домен?</strong> Заместить доступные всем посты из указанного аккаунта на главную страницу или составить список ленты. Объектами являются посты, полученные сервером (из распределенной ленты)."
    new:
      title: Добавить новую подписку на домен
  favourite_domains:
    add_new: Добавить новый
    errors:
      limit: У Вас уже добавлено максимальное количество доменов в избранном
    hint_html: "<strong>Что такое избранные домены?</strong> Они используются только Вами и являются инструментами, помогающими браузеру использовать домены. Вы можете быстро переключаться между лентами."
  favourite_tags:
    add_new: Добавить новый
    errors:
      limit: У Вас уже добавлено максимальное количество хэштегов в избранном
    hint_html: "<strong>Что такое избранные хэштеги?</strong> Они используются только Вами и являются инструментами, помогающими браузеру использовать хэштеги. Вы можете быстро переключаться между лентами."
  follow_tags:
    edit:
      title: Изменить
    hint_html: "<strong>Что такое подписки-хэштеги? </strong> Это подборка хэштегов, по которым Вы переходили. Полученные сервером хэштеги из постов, один из которых указан здесь, является добавленным на главную страницу или в список ленты."
    new:
      title: Добавить новый хэштег-подписку
  keyword_subscribes:
    disabled: Не активный
    edit:
      title: Изменить
    enabled: Активный
    errors:
      duplicate: Такие данные уже были зарегистрированы
      limit: Вы достигли максимальное количество "Присоединенных ключевых слов", которое может быть зарегистрировано
      regexp: 'Ошибка регулярного выражения: %{message}'
    hint_html: "<strong>Что означает поддерживание ключевых слов?</strong> Заместить доступный всем пост, который соответствует одному из указанных слов или регулярному выражению на главную страницу или составить список ленты. Объектами являются посты, полученные сервером (из распределенной ленты)."
    ignore_block: Игнорировать
    ignorecase:
      disabled: Деликатный
      enabled: Игнорировать
    index:
      delete: Удалить
      title: Подписаться на ключевое слово
    new:
      title: Добавить подписку на новое ключевое слово
    regexp:
      disabled: Ключевое слово
      enabled: Регулярное выражение
  lists:
    add_new: Добавить новый список
    home: Главная
  notification_mailer:
    emoji_reaction:
      body: 'На Ваш пост отреагировал эмодзи %{name}:'
      subject: "%{name} ответил эмодзи на Ваш пост"
      title: Новый ответ в виде эмодзи
  preferences:
    fedibird_features: Возможности Fedibird
  relationships:
    interrelationship: Взаимосвязь
    one_way: Односторонний
  settings:
    account_subscribes: Подписаться на аккаунт
    domain_subscribes: Подписаться на домен
    favourite_domains: Избранные домены
    favourite_tags: Избранные хэштеги
    follow_and_subscriptions: Подписки и подписанное
    follow_tags: Следуемые хэштеги
    keyword_subscribes: Подписаться на ключевые слова
  status_expire:
    validations:
      expire_in_the_past: Этот срок действия уже истек. Вы не можете указать истекший срок действия до времени публикации.
      invalid_expire_action: Указанное действие с истекшим сроком является недопустимым.
      invalid_expire_at: Указан недопустимый срок действия.
  statuses:
    errors:
      duration_too_long: слишком долгое время
      duration_too_short: еще слишком рано
    visibilities:
      direct_long: Показывать только упомянутым пользователям
      limited: Круг
      limited_long: Показывать только пользователям круга
      mutual: Общие
      mutual_long: Показывать толькоо общим подпсчикам
