ru:
  simple_form:
    hints:
      defaults:
        setting_enable_limited_timeline: Включить ограниченный вид главной страницы для отображения приватности, кругов и личных сообщений
        setting_enable_reaction: Включить отображение откликов в ленте и показывать кнопку ответа
        setting_follow_button_to_list_adder: Изменить свойства Подписки / Кнопка подписаться - открыть диалоговое окно где Вы можете выбрать список подписки / подписаться или отказаться получать на домашней странице
        setting_place_tab_bar_at_bottom: Во время использования сенсорного устройства Вы можете работать с вкладками в пределах достижения Ваших пальцев.
        setting_show_bookmark_button: При выключении вызываемая закладка будет в стандарном расположении Mastodon (в меню на панели действий)
        setting_show_follow_button_on_timeline: Вы можете легко проверить статусы подписок и быстро построить список подписок
        setting_show_followed_by: 'Цвет кнопки подписки изменяется в зависимости от статуса подписки (серый: нет взаимосвязанных подписок, желтый: подписанные на Вас пользователи, голубой: Ваши подписки на других пользователей, зеленый: взаимные подписки)'
        setting_show_navigation_panel: Показывать панель навигации у правого поля пользовательского интерфейса
        setting_show_quote_button: Выберите, отображать либо не отображать кнопку на панели действий. Это действие не активирует/отключает функцию цитирования.
        setting_show_reply_tree_button: В случае отключения кнопка "Показать обсуждение" будет отображаться только если отправитель поста отвечает самому себе в ряде постов
        setting_show_subscribe_button_on_timeline: Вы можете легко проверить статус Ваших подписок и быстро создать их список
        setting_show_tab_bar_label: При добавлении списка и других элементов на панель вкладок рекомендуется показывать ярлык, т. к. отличить их только по одному значку нельзя
        setting_show_target: Активировать функцию переключения между опубликованием адресата и подпиской / подписанием на адресата
      domain_subscribe:
        domain: Укажите имя доменное имя сервера на который Вы хотите подписаться
        exclude_reblog: Убрать продвигаемые посты из подписки
        media_only: Ориентированность только на посты с прикрепленным медиа файлом
      follow_tag:
        media_only: Ориентированность только на посты с прикрепленным медиа файлом
        name: 'Указать название хештега, на который Вы хотите подписаться, без "#" '
      form_account_subscribe:
        acct: Указать имя пользователя@домен аккаунта, на который Вы хотите подписаться
        media_only: Нацеленность только на посты с прикрепленным медиа файлом
        show_reblogs: Показывать продвигаемые посты подписок
      keyword_subscribe:
        exclude_keyword: Перечислите многократно повторяющиеся исключаемые слова, разделяя их запятыми (или используйте регулярные выражения)
        ignore_block: Вы можете расставить приоритеты для подписок на ключевые слова, сохраняя при этом весь домен заблокированным
        keyword: Перечислите многократно повторяющиеся исключаемые слова, разделяя их запятыми (или используйте регулярные выражения)
        media_only: Ориентированность только на посты с прикрепленным медиа файлом
        name: Дополнительный
    labels:
      defaults:
        setting_enable_limited_timeline: Включить ограниченную ленту событий
        setting_enable_reaction: Сделать реакцию видимой
        setting_show_navigation_panel: Показать панель навигации
      domain_subscribe:
        domain: Домен
        exclude_reblog: Исключить продвижение
        list_id: Целевая лента событий
        media_only: Только медиафайлы
        reblog: Продвигать
        timeline: Лента событий
      favourite_domain:
        name: Домен
      favourite_tag:
        name: Хэштег
      follow_tag:
        list_id: Целевая лента событий
        media_only: Только медиафайлы
        name: Название тега
        timeline: Лента событий
      form_account_subscribe:
        acct: Профиль
        list_id: Целевая лента событий
        media_only: Только медиафайлы
        reblog: Продвигать
        show_reblogs: Показать продвижение
        timeline: Лента событий
      keyword_subscribe:
        ignore_block: Не обращать внимание на блокировку домена Пользователя
        keyword: Список ключевых слов или регулярных выражений
        list_id: Целевая лента событий
        media_only: Только медиафайлы
        name: Имя
        regexp: Использовать регулярные выражения для ключевых слов
      keyword_subscribes:
        disabled: Состояние
        ignore_block: Заблокировать
        keyword: Строка
        media_only: Медиа файл
        name: Имя
        regexp: Тип
        timeline: Лента событий
      notification_emails:
        emoji_reaction: На Ваш пост направлен эмодзи
        reaction: На Ваш пост поступил отклик
