#!/usr/bin/env node

// Builds app/javascript/mastodon/features/emoji/emoji_unicode_ja_readings.js
// from a local Mozc emoji_data.tsv. This does not run during the WebUI build
// and does not download anything.
//
// Source: https://github.com/google/mozc/blob/4517e51d53063397222adb5512c7ad972b17c181/src/data/emoji/emoji_data.tsv
// License: BSD 3-Clause, Google Inc. See emoji_unicode_ja_readings.LICENSE.
//
// Usage:
//   node script/generate_emoji_unicode_ja_readings.js /path/to/emoji_data.tsv

const fs = require('fs');
const path = require('path');

const VARIATION_SELECTORS = /[\uFE0E\uFE0F]/g;
const OUTPUT = path.join(
  __dirname,
  '../app/javascript/mastodon/features/emoji/emoji_unicode_ja_readings.js',
);

function normalizeUnicodeEmojiSearchKey(value) {
  return String(value || '').replace(VARIATION_SELECTORS, '');
}

function supportedEmojiKeys() {
  const mapping = require('../app/javascript/mastodon/features/emoji/emoji_unicode_mapping_light');
  const keys = new Set();

  Object.keys(mapping).forEach((emoji) => {
    const key = normalizeUnicodeEmojiSearchKey(emoji);

    if (key) {
      keys.add(key);
    }
  });

  return keys;
}

function readingsFromCell(cell) {
  const seen = new Set();
  const readings = [];

  String(cell || '').split(/\s+/).forEach((reading) => {
    if (!reading || seen.has(reading)) {
      return;
    }

    seen.add(reading);
    readings.push(reading);
  });

  return readings;
}

function parseTsv(tsvPath) {
  const supported = supportedEmojiKeys();
  const map = new Map();
  let rows = 0;
  let skipped = 0;

  fs.readFileSync(tsvPath, 'utf8').split(/\r?\n/).forEach((line) => {
    if (!line || line.startsWith('#')) {
      return;
    }

    const columns = line.split('\t');
    const emoji = columns[1];
    const key = normalizeUnicodeEmojiSearchKey(emoji);
    const readings = readingsFromCell(columns[2]);

    rows += 1;

    if (!key || !readings.length || !supported.has(key)) {
      skipped += 1;
      return;
    }

    const existing = map.get(key) || [];
    const seen = new Set(existing);

    readings.forEach((reading) => {
      if (!seen.has(reading)) {
        seen.add(reading);
        existing.push(reading);
      }
    });

    map.set(key, existing);
  });

  return { map, rows, skipped, supported: supported.size };
}

function render(map) {
  const entries = Array.from(map.keys()).sort().map((key) => (
    `  ${JSON.stringify(key)}: ${JSON.stringify(map.get(key))},`
  ));

  return `/* eslint-disable */
// Generated by script/generate_emoji_unicode_ja_readings.js.
// Do not edit by hand.
//
// Reading/search terms extracted from Mozc src/data/emoji/emoji_data.tsv
// at 4517e51d53063397222adb5512c7ad972b17c181 (Emoji 17.0 / CLDR 48).
// https://github.com/google/mozc/blob/4517e51d53063397222adb5512c7ad972b17c181/src/data/emoji/emoji_data.tsv
//
// Copyright 2010-2018, Google Inc. All rights reserved.
// Licensed under the BSD 3-Clause License. See emoji_unicode_ja_readings.LICENSE.
// Only the emoji character and its Mozc reading/search terms are kept, and only for
// emoji present in emoji_unicode_mapping_light. Variation selectors are
// removed from the lookup key. Stored reaction values are not rewritten.
export default {
${entries.join('\n')}
};
`;
}

function main() {
  const tsvPath = process.argv[2];

  if (!tsvPath) {
    console.error('Usage: node script/generate_emoji_unicode_ja_readings.js /path/to/emoji_data.tsv');
    process.exit(1);
  }

  const { map, rows, skipped, supported } = parseTsv(tsvPath);
  const source = render(map);

  fs.writeFileSync(OUTPUT, source);
  console.warn(JSON.stringify({
    tsvRows: rows,
    skipped,
    supportedEmoji: supported,
    generatedEntries: map.size,
    bytes: Buffer.byteLength(source),
  }, null, 2));
}

main();
